# Generated by Django 5.2.8 on 2025-12-08 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hostel.room'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
